name: Android Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up NDK
        uses: actions/setup-android@v3
        with:
          api-level: 33  # Replace with your target API level
          ndk-version: '25.2.9519653'  # Replace with your NDK version

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Build library
        run: ./gradlew build

  # Additional steps for testing, code coverage, etc.
