name: Android Library CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: gradle

      - name: Set up NDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35  # Replace with your target API level
          ndk-version: '27.2.12479018'  # Replace with your NDK version

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build library
        run: ./gradlew birchBeer:build

      - name: store lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: birchBeer
          path: birchBeer/build/outputs/aar/*.aar

  # Additional steps for testing, code coverage, etc.
